// This file has been autogenerated from a class added in the UI designer.

using System;
using AVFoundation;
using AVKit;
using Foundation;
using tvChannel9.Classes;
using UIKit;

namespace tvChannel9
{
	public partial class VideoCollectionViewController : UICollectionViewController
	{
		#region Computed Properties
		public VideoCollectionView Collection {
			get { return CollectionView as VideoCollectionView; }
		}

		#endregion

		#region Constructors
		public VideoCollectionViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			// Save link to controller
			Collection.ParentController = this;
		}
        #endregion

        private AVPlayerViewController _player;

        public AVPlayerViewController PlayerController()
        {
            if (_player == null)
                _player = new AVPlayerViewController();
            return _player;
        }

        public void PlayStream(VideoItem item)
        {
   //         var player = PlayerController();
   //         NSUrl url = new NSUrl(item.VideoUrl);
   //         player.Player = new AVFoundation.AVPlayer(url);
			//player.Player.Play();
			//this.NavigationController.PresentViewController(player, true, () => player.Player.Play());
        }
	}
}
