// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace tvChannel9
{
	public partial class VideoCollectionViewController : UICollectionViewController
	{
		#region Computed Properties
		public VideoCollectionView Collection {
			get { return CollectionView as VideoCollectionView; }
		}
		#endregion

		#region Constructors
		public VideoCollectionViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			// Save link to controller
			Collection.ParentController = this;
		}
		#endregion
	}
}
